# Generated by Django 5.2.9 on 2025-12-23 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testrecord",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testrecord",
            name="report_image",
            field=models.ImageField(blank=True, null=True, upload_to="reports/"),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="certificate_image",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="testrecord",
            name="test_result",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
