# Generated by Django 5.2.9 on 2025-12-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_testrecord_patient_testrecord_report_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrecord",
            name="symptoms",
            field=models.CharField(
                choices=[
                    ("Cough", "Cough"),
                    ("Fever", "Fever"),
                    ("Wheezing", "Wheezing"),
                    ("Shortness of Breath", "Shortness of Breath"),
                    ("Sore Throat", "Sore Throat"),
                ],
                default="Cough",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="testrecord",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("PCR", "RT-PCR (Polymerase Chain Reaction)"),
                    ("Antigen", "Antigen Rapid Test"),
                    ("Culture", "Viral Culture"),
                    ("Serology", "Serology (Blood Test)"),
                ],
                default="PCR",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="testrecord",
            name="date_of_test",
            field=models.DateField(help_text="Date sample was collected"),
        ),
        migrations.AlterField(
            model_name="testrecord",
            name="report_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload ID Proof or Doctor's Referral",
                null=True,
                upload_to="reports/",
            ),
        ),
    ]
