# Generated by Django 5.2.9 on 2025-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_testrecord_symptoms_testrecord_test_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrecord",
            name="aadhaar_number",
            field=models.CharField(
                default="000000000000",
                help_text="12-digit Aadhaar Number",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="testrecord",
            name="phone_number",
            field=models.CharField(
                default="0000000000",
                help_text="Patient Phone Number for OTP",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="testrecord",
            name="symptoms",
            field=models.CharField(
                choices=[
                    ("Cough", "Cough"),
                    ("Fever", "Fever"),
                    ("Wheezing", "Wheezing"),
                    ("Shortness of Breath", "Shortness of Breath"),
                    ("Sore Throat", "Sore Throat"),
                    ("Runny Nose", "Runny Nose"),
                    ("Other", "Other"),
                ],
                default="Cough",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vaccinationrecord",
            name="vaccine_type",
            field=models.CharField(
                choices=[
                    ("Toxoid", "Toxoid"),
                    ("Polysaccharide", "Polysaccharide"),
                    ("mRNA", "mRNA"),
                    ("Other", "Other"),
                ],
                default="Toxoid",
                max_length=50,
            ),
        ),
    ]
