# Generated by Django 5.2.9 on 2025-12-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_testrecord_aadhaar_number_testrecord_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrecord",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
