# Generated by Django 5.2.9 on 2025-12-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_testrecord_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinationrecord",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
